import Link from "next/link";
import { Boxes, Compass, Home, Layers3, MessageCircle, Settings, Sparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { CollectionPanel } from "@/components/collection-panel";
import { FeedComposer } from "@/components/feed-composer";

export default async function FeedPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const name = String(user?.user_metadata?.full_name || user?.email?.split("@")[0] || "Member");
  const initials = name.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "A";
  const { data: collection } = user ? await supabase.from("assets").select("id, category, title, image_paths").eq("user_id", user.id).order("created_at", { ascending: false }) : { data: [] };
  const { data: posts } = await supabase.from("posts").select("id, body, created_at, profiles(display_name, username)").order("created_at", { ascending: false }).limit(30);
  return <main className="app-page"><aside className="app-sidebar"><Link className="wordmark" href="/">AETHER<span>.</span></Link><nav><Link className="active" href="/app/feed"><Home size={17} />Feed</Link><Link href="/app/explore"><Compass size={17} />Explore</Link><Link href="/app/circles"><Layers3 size={17} />Circles</Link><Link href="/app/collection"><Boxes size={17} />Collection</Link><Link href="/app/messages"><MessageCircle size={17} />Messages</Link><Link href="/app/settings"><Settings size={17} />Settings</Link></nav><div className="sidebar-profile"><span className="avatar">{initials}</span><span>{name}</span></div></aside><aside className="app-collectionbar"><CollectionPanel assets={collection ?? []} /></aside><section className="feed"><div className="feed-heading"><h1>Good evening, {name}.</h1><p>{new Intl.DateTimeFormat("en-US", { dateStyle: "full" }).format(new Date())}</p></div><FeedComposer initials={initials} />{posts?.length ? posts.map((post) => { const profile = Array.isArray(post.profiles) ? post.profiles[0] : post.profiles; const postName = profile?.display_name || profile?.username || "Member"; return <article className="post" key={post.id}><div className="post-top"><span className="avatar">{postName.slice(0, 2).toUpperCase()}</span><div><strong>{postName}</strong><p>@{profile?.username || "member"} · {new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(post.created_at))}</p></div></div><p className="post-copy">{post.body}</p></article>; }) : <div className="feed-empty"><Sparkles size={18} /><h2>Your feed is ready for its first note.</h2><p>Share a thought or explore the network to begin your AETHER experience.</p><Link href="/app/explore">Explore the network <span>↗</span></Link></div>}</section><aside className="app-rightbar"><div className="rightbar-heading"><span className="eyebrow">Your network</span><Sparkles size={16} /></div><article className="sponsor-card"><span className="sponsor-label">Membership</span><div className="sponsor-mark">A</div><h2>AETHER SOCIETY</h2><p>Your private network is ready to explore.</p><Link href="/app/circles">Explore circles <span>↗</span></Link></article></aside></main>;
}
