import Link from "next/link";
import { Compass, Home, Layers3, MessageCircle, Search, Settings, Sparkles, Users } from "lucide-react";
import { ThemeToggle } from "@/components/theme-toggle";

const posts = [{ name: "Lena Moreau", handle: "@lenamoreau", time: "14m", copy: "The most interesting rooms are the ones where no one needs to announce why they belong there.", circle: "The Salon" }, { name: "Alexander Wei", handle: "@awei", time: "1h", copy: "A quiet afternoon at the foundation. The new collection arrives next Thursday.", circle: "Art & Design" }];

export default function FeedPage() {
  return <main className="app-page"><aside className="app-sidebar"><Link className="wordmark" href="/">AETHER<span>.</span></Link><nav><Link className="active" href="/app/feed"><Home size={17} />Feed</Link><Link href="/app/explore"><Compass size={17} />Explore</Link><Link href="/app/circles"><Layers3 size={17} />Circles</Link><Link href="/app/messages"><MessageCircle size={17} />Messages</Link><Link href="/app/settings"><Settings size={17} />Settings</Link></nav><div className="sidebar-profile"><span className="avatar">LM</span><span>Lena Moreau</span></div></aside><section className="feed"><header className="app-topbar"><Link className="app-topbar-brand" href="/app/feed">AETHER<span>.</span></Link><label className="search-bar"><Search size={15} /><span className="sr-only">Search AETHER</span><input type="search" placeholder="Search AETHER" /></label><div className="topbar-actions"><ThemeToggle /><span className="avatar">LM</span></div></header><div className="feed-heading"><h1>Good evening, Lena.</h1><p>Tuesday, September 15, 2026</p></div><div className="composer"><span className="avatar">LM</span><span>Share something considered...</span><button>Post</button></div>{posts.map((post) => <article className="post" key={post.handle}><div className="post-top"><span className="avatar">{post.name.split(" ").map((part) => part[0]).join("")}</span><div><strong>{post.name}</strong><p>{post.handle} · {post.time}</p></div><span className="post-circle">{post.circle}</span></div><p className="post-copy">{post.copy}</p><div className="post-actions"><span>♡ 18</span><span>○ 4</span><span>↗ Share</span></div></article>)}</section><aside className="app-rightbar"><div className="rightbar-heading"><span className="eyebrow">Curated for you</span><Sparkles size={16} /></div><article className="sponsor-card"><span className="sponsor-label">Sponsored</span><div className="sponsor-mark">N</div><h2>NORTH / HOUSE</h2><p>Objects with a point of view. Discover the autumn collection.</p><a href="#sponsored">Explore <span>↗</span></a></article><section className="people-card"><div className="rightbar-heading"><span className="eyebrow">People to know</span><Users size={16} /></div><div className="person-row"><span className="avatar">MC</span><div><strong>Matteo Conti</strong><p>Architecture · Milan</p></div><button>Follow</button></div><div className="person-row"><span className="avatar">SK</span><div><strong>Sarah Kim</strong><p>Philanthropy · Seoul</p></div><button>Follow</button></div></section></aside></main>;
}
