import Link from "next/link";
import { ArrowLeft, MapPin, MessageCircle, UserPlus } from "lucide-react";

type Member = { name: string; initials: string; role: string; location: string; bio: string; circle: string; photo: string; interests: string[]; stats: [string, string][]; netWorth: string; wall: { title: string; text: string; time: string }[] };

const members: Record<string, Member> = {
  "matteo-conti": { name: "Matteo Conti", initials: "MC", role: "Architect & collector", location: "Milan, Italy", bio: "Working at the edge of architecture, material, and the spaces that hold a life.", circle: "Art & Design", photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=80", interests: ["Modernism", "Material culture", "New spaces"], stats: [["12", "circles"], ["184", "connections"], ["28", "notes"]], netWorth: "$84M", wall: [{ title: "On collecting slowly", text: "The best objects do not ask for attention. They earn it over time, through use, care, and the stories that gather around them.", time: "2 days ago" }, { title: "A new room in Milan", text: "There is a particular pleasure in finding the right proportion before choosing a single piece of furniture.", time: "1 week ago" }] },
  "sarah-kim": { name: "Sarah Kim", initials: "SK", role: "Philanthropist", location: "Seoul, South Korea", bio: "Building patient, practical systems for a more generous future.", circle: "Philanthropy", photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=80", interests: ["Education", "Climate", "Civic life"], stats: [["9", "circles"], ["226", "connections"], ["41", "notes"]], netWorth: "$126M", wall: [{ title: "The long view", text: "Small, durable interventions are often more generous than grand gestures. Patience is a form of capital.", time: "4 days ago" }] },
  "lena-moreau": { name: "Lena Moreau", initials: "LM", role: "Investor & curator", location: "Paris, France", bio: "Following the people and ideas making the next decade more interesting.", circle: "The Salon", photo: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=700&q=80", interests: ["Art", "Venture", "Travel"], stats: [["16", "circles"], ["312", "connections"], ["56", "notes"]], netWorth: "$210M", wall: [{ title: "Three signals", text: "The most compelling founders I meet are patient about the outcome and impatient about the work.", time: "Yesterday" }] },
  "alexander-wei": { name: "Alexander Wei", initials: "AW", role: "Family office principal", location: "Singapore", bio: "Long-term thinking across art, enterprise, and place.", circle: "Family Offices", photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=80", interests: ["Enterprise", "Art", "Stewardship"], stats: [["11", "circles"], ["198", "connections"], ["32", "notes"]], netWorth: "$480M", wall: [{ title: "On stewardship", text: "Ownership is only the first chapter. The more interesting question is what a thing becomes in your care.", time: "3 days ago" }] },
};

export default async function ProfilePage({ params }: { params: Promise<{ username: string }> }) {
  const { username } = await params;
  const member = members[username] ?? members["matteo-conti"];
  return <main className="profile-page"><header className="profile-header"><Link className="wordmark" href="/app/feed">AETHER<span>.</span></Link><Link className="profile-back" href="/app/circles"><ArrowLeft size={15} /> Back to circles</Link></header><section className="profile-hero"><div className="profile-avatar-large" style={{ backgroundImage: `url(${member.photo})` }}><span>{member.initials}</span></div><div className="profile-content"><p className="eyebrow">{member.circle}</p><h1 className="section-title">{member.name}</h1><p className="profile-role">{member.role}</p><p className="profile-location"><MapPin size={14} /> {member.location}</p><p className="profile-bio">{member.bio}</p><div className="profile-actions"><button className="profile-action"><UserPlus size={15} /> Follow</button><button className="profile-action secondary"><MessageCircle size={15} /> Message</button></div></div></section><nav className="profile-tabs" aria-label="Profile sections"><a className="active" href="#wall">Wall</a><a href="#connections">Connections</a><a href="#about">About</a></nav><section className="profile-body"><div className="profile-wall" id="wall"><div className="wall-heading"><p className="eyebrow">{member.name.split(" ")[0]}&apos;s wall</p><span>Recent notes</span></div>{member.wall.map((post) => <article className="wall-post" key={post.title}><div className="wall-post-meta"><span className="avatar">{member.initials}</span><div><strong>{member.name}</strong><p>{post.time}</p></div></div><h2>{post.title}</h2><p>{post.text}</p><div className="post-actions"><span>♡ 24</span><span>○ 6</span><span>↗ Share</span></div></article>)}</div><aside className="profile-aside" id="about"><div className="profile-stat-feature"><span className="eyebrow">Estimated net worth</span><strong>{member.netWorth}</strong><small>Private profile · verified by AETHER</small></div><div className="profile-stats" id="connections">{member.stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="profile-interests"><p className="eyebrow">Interests</p><div>{member.interests.map((interest) => <span key={interest}>{interest}</span>)}</div></div></aside></section></main>;
}
